### ISSUE TITLE
Won't/can't unit test the generated state_id_to_string() or a ROOT_exit() functions

### ISSUE THREAD

**Issue by rahmant3** [StateSmith/StateSmith#105]
Hi, this is a great project! =) 

I like unit testing the generated source code to verify the behavior but I don't want to unit test these functions. Since I don't unit test them, my code coverage metrics show them as not covered.

- ...state_id_to_string() -- I don't personally use this function at all so it would be nice if this was excluded from the code coverage metrics
- ROOT_exit() -- This function is unreachable as my state machine doesn't typically exit (they just run forever).

The following comments could be added before/after these functions to exclude them from code coverage metrics:

```
// LCOV_EXCLUDE_START
// GCOV_EXCLUDE_START
// GCOVR_EXCLUDE_START
... function goes here ...
// LCOV_EXCLUDE_STOP
// GCOV_EXCLUDE_STOP
// GCOVR_EXCLUDE_STOP
```

This should exclude the function from being picked by lcov, gcov, and gcovr.

**Comment by adamfk** [comment]
Great suggestion!

**Comment by adamfk** [comment]
Completed as part of #114. See https://github.com/StateSmith/StateSmith-examples/tree/main/user-post-process

Video tutorial will be uploaded soon-ish to https://www.youtube.com/@statesmith

**Comment by adamfk** [comment]
Video links:
* [Removing state id to string function](https://www.youtube.com/watch?v=UYL6Qzoyxwo&t=614s)
* [Surrounding a function with code coverage annotations ](https://www.youtube.com/watch?v=UYL6Qzoyxwo&t=810s)
