### ISSUE TITLE
Suggestion: sync with UML standard "enter" vs "entry"

### ISSUE THREAD

**Issue by iamjuing** [StateSmith/StateSmith#108]
Many thanks for this effort! I was looking of such a generator for some time already.

Just a suggestion ... it would be nice to sync with UML terminology and use "entry" keyword instead of "enter" (perhaps both, to be backward compatible(?)).

**Comment by adamfk** [comment]
@iamjuing I like the backwards compatible idea. Thanks for the suggestion! Will implement soon.
