### ISSUE TITLE
replace "#pragma once" with include guard

### ISSUE THREAD

**Issue by iamjuing** [StateSmith/StateSmith#112]
"#pragma once" is non-standard compiler extensions. Although supported by many compilers, I would still recommend to avoid it in favour of the regular include guard generated from the FSM name.

**Comment by adamfk** [comment]
I was wondering about this myself recently. Pragma once is great for code/file headers that might be copy pasted around, but that probably isn't going to happen with the generated FSM code.

Do you have a suggested default rendering setting? If state machine name is `MySm` include guard would be 

```c
#ifndef MYSM_H
#define MYSM_H

#endif /* MYSM_H */
```

We can also add a customization to override the default rendering.

**Comment by iamjuing** [comment]
Looks good to me.
