### ISSUE TITLE
C# expansions (powerful) in diagrams

### ISSUE THREAD

**Issue by adamfk** [StateSmith/StateSmith#118]
This will be a decent amount of work, but is an important step towards a stand alone tool. Let me know if you'd like to help design and or implement.

Tasks
- [ ] add render config item
- [ ] compile with roslyn. Include proper error messages.
- [ ] ??? draw.io plugin that makes it easier to edit c# expansions code in draw.io. Can be difficult to read regular un-highlighted code. Click button, takes you to [statesmith github.io page](https://stackoverflow.com/questions/63179813/how-to-run-the-monaco-editor-from-a-cdn-like-cdnjs) populated with diagram text. Highlights the code and helps with editing. Someday bring monaco editor into draw.io (but I suspect I'll need help with that).
- [ ] or alternatively, just have user copy paste code into blank vscode file. It auto detects C# and has better syntax highlighting than latest monaco version. vscode highlighting is even better if you wrap in a bogus class though.

# Implementation options
We could embed a javascript engine and have a lot of confidence in security, but then we add another syntax for expansions which I'm not a fan of. Also adds more complexity and size to StateSmith.

I'm leaning towards using Roslyn.

In the diagram:

![image](https://user-images.githubusercontent.com/274012/221393194-8bbc3a95-5f92-4143-ad2e-cbd205f21e21.png)

If you paste from vscode and enable html label in draw.io, you could see this instead:

![image](https://user-images.githubusercontent.com/274012/221393222-8308dded-2124-47b8-8920-dc66cff1a2b8.png)

One day we could have our syntax highlighting live.

leading with `public` is optional and can be omitted

![image](https://user-images.githubusercontent.com/274012/221393315-eedf30f7-66f7-4615-a741-f2f434b1ea35.png)

We could also potentially allow the leading `string` to be omitted (but this is more difficult and requires new custom parsing which I would rather avoid):

![image](https://user-images.githubusercontent.com/274012/221393301-3fa97161-6e27-4c73-a68f-ff24795451c4.png)

## Transformed Into
```c#
using StateSmith.Input.Expansions; // for UserExpansionScriptBase
public class DiagramExpansion_DiagramIdHere : UserExpansionScriptBase
{
    public string boom3() => "light_boom3()";

    public string timer1_started_at_ms => AutoVarName();
    public string option_value         => AutoVarName();
    
    public string set_option_class(string class_name) => $"{option_value} = PlayerClass_{class_name}";
    public string time_ms => "PortApi_get_time_ms()";
    public string reset_timer1() => $"{timer1_started_at_ms} = {time_ms}";
}
```

Then parsed with Roslyn to ensure no security concerns.

## Security
Right now, expansions can execute any C# code. This is great if you want to be able to do something specialized. If you need that, you'll have to run StateSmith from a .cs or .csx file.

```c#
using StateSmith.Input.Expansions;
public class DiagramExpansion_DiagramIdHere : UserExpansionScriptBase
{
    public string option_value         => System.SomethingDangerous("","");
}
```

### Fail on any SimpleMemberAccessExpression

![image](https://user-images.githubusercontent.com/274012/221393862-af5c7d13-1a47-4ab6-bef2-b00d7eadaca5.png)
![image](https://user-images.githubusercontent.com/274012/221393855-189dc189-be13-4eff-949d-de6b55663bfe.png)

### Need to prevent any implicit usings.
Need to look into.

### Need to prevent object creation
Can fail on `NewKeyword` token.

![image](https://user-images.githubusercontent.com/274012/221393957-2bd9beb2-775d-4d74-b91d-c8e8d4559fdf.png)

![image](https://user-images.githubusercontent.com/274012/221393967-211945cd-5ff8-4ec1-b7ca-e6c99b465df7.png)

![image](https://user-images.githubusercontent.com/274012/221393990-e9f91e26-35e8-4a5b-882e-71e478a82c28.png)

![image](https://user-images.githubusercontent.com/274012/221393991-b71b3d02-a1a0-4f6d-9ebc-df15126eac78.png)

### Anything else to consider?
Definitely not future proof as C# language can evolve. I wonder if there is a way to ask Roslyn to parse as a certain C# version? Would be safer to only allow certain syntax or use js engine.

**Comment by PopeAndrewJ** [comment]
I wonder if something like 
[DotNetIsolator ](https://github.com/SteveSandersonMS/DotNetIsolator)  will come out of  experimental any time soon..

**Comment by adamfk** [comment]
@PopeAndrewJ that is a cool project! Thanks for sharing it. It would definitely help solve this problem.

How concerned do you think we should be about security and potentially malicious code inside an expansion? Should StateSmith just prompt the user if it is going to execute expansion code that they haven't already approved?

**Comment by adamfk** [comment]
Closing for now. I think it's more complicated and powerful than we need in diagrams. We will support simple expansions in diagrams, but if you need full power expansions, then use .csx scripts.
