### ISSUE TITLE
the generator fails on action between choice points

### ISSUE THREAD

**Issue by iamjuing** [StateSmith/StateSmith#135]
This valid use case does not seem to work:
![image](https://user-images.githubusercontent.com/125978139/224708715-daa3ff45-3883-4379-b41e-66d2c90df42b.png)

When the `action()` is removed from the transition, it passes.
StateSmith 0.7.16

**Comment by adamfk** [comment]
Can you try `/ action();` ? The UML spec that we follow requires a forward slash before actions.

More info on behaviors here: https://github.com/StateSmith/StateSmith/wiki/Behaviors

**Comment by iamjuing** [comment]
That works. Thanks.
