### ISSUE TITLE
Shortest Fully Qualified Name (FQN)

### ISSUE THREAD

**Issue by adamfk** [StateSmith/StateSmith#138]
See https://github.com/StateSmith/StateSmith/issues/137#issuecomment-1467561096

Below is an example design to discuss. Do the Short FQNs look correct? The diagram is an editable draw.io svg in case anyone wants to modify it.

![MySm1 drawio](https://user-images.githubusercontent.com/274012/225024361-c5faf0d0-738a-44ce-b6e8-f12bb2ff94b7.svg)

**Comment by iamjuing** [comment]
Nice :) Thanks for the picture.
Looks correct, a bit surreal though. Anyway, I'm sure, with meaningful state names, it would look ok.

I would definitely prefer this over manually resolving conflicts with `$mod prefix`, even if it meant to break naming conventions when it comes to identifier length (who cares in the generated code).

**Comment by adamfk** [comment]
I'm going to start playing around with this and see how it goes.

**Comment by adamfk** [comment]
The below graph isn't a state machine graph, it is a hierarchy/inheritance graph. `FOOD` is a substate of `FOOD_BEV`.

I think I have a basic algorithm now. For every state that has a conflicting name (like `NONE` or `COLD`), find the deepest LCA (least common ancestor) for a conflict pair, then go one deeper than the LCA (if possible). That forms the ancestor to use to prefix the state.

For example `HOT__NONE` would see `FOOD` as its deepest LCA of all other `NONE` conflicting states. It then goes one deeper to `HOT` and uses that as its prefix.

`DRINK__NONE` has `FOOD_BEV` as its deepest LCA with all other `NONE` conflicting states. It then goes one deeper to `DRINK` and uses that as its prefix.

![Menu2 drawio](https://user-images.githubusercontent.com/274012/225216387-261e3487-6824-4f1f-9360-adf90652c6dd.svg)

Diagram is an editable draw.io svg.

**Comment by iamjuing** [comment]
An alternative that I had in mind when opening the issue:
Prefix only direct parent, until there are no duplicates. If there are still duplicates, prefix all with parent's parent and so on.

![bottom-to-top](https://user-images.githubusercontent.com/125978139/225307799-763b0620-c29d-4035-b4bf-a941f0fe6f94.svg)

It probably doesn't matter as it has no impact on FSM behavior. It's just about which approach looks more appropriate in a log or, how easy it is to debug it. I have no preference.

**Comment by adamfk** [comment]
I wondered about that too. I'm not sure which version is better for understanding. The earlier version that I posted is likely to have shorter names though. If it is easy enough, I'll make a setting that we can play with.

**Comment by adamfk** [comment]
@iamjuing Can you try the feature out? Details here: https://github.com/StateSmith/StateSmith/wiki/State-Names
