### ISSUE TITLE
extend file header comment with more meta data

### ISSUE THREAD

**Issue by iamjuing** [StateSmith/StateSmith#152]
- StateSmith version that generated the file
- UTC time/date of generation etc.

**Comment by adamfk** [comment]
Thanks for the report. Added in next release.

I made it a setting to enable date and time of code generation because it may add noise to workflows that use git.

Details and examples here: https://github.com/StateSmith/StateSmith/blob/8db2d31721569f1be2b28fbd65995866c2997081/CHANGELOG.md#added
