### ISSUE TITLE
draw.io - support note shapes

### ISSUE THREAD

**Issue by adamfk** [StateSmith/StateSmith#192]
Good suggestion from: https://github.com/StateSmith/StateSmith/issues/190#issuecomment-1532501709

Might as well support all of the draw.io note shapes :)

![notes drawio](https://user-images.githubusercontent.com/274012/236075116-2a91834d-c1cc-449e-a8ce-5b5b24cff269.svg)

This would be a nice alternative to the standard `$NOTES` shapes. Both will be supported.

![image](https://user-images.githubusercontent.com/274012/236075286-e95fd728-b1ba-4e66-b5dd-d0588f9cba34.png)

**Comment by iamjuing** [comment]
To be general, would `shape=.*note.*` regex work safely?

**Comment by adamfk** [comment]
I'm a bit hesitant to use a regex here because I can't be sure. Right now we only have 3 notes shapes that I'm aware of so I think I'll just stick with testing against those three for now. If we find users wanting to add custom notes shapes, we could also support a custom `STATESMITH_NOTES_VERTEX=1;` style. Safe and then can be applied to whatever users want.
