### ISSUE TITLE
Simply couldn't get it working

### ISSUE THREAD

**Issue by lewsut** [StateSmith/StateSmith#220]
I'm very interested in this project but the tutorials did nothing for me, on a windows machine I have no idea what's going on, followed your youtube videos with a complete failure. Probably a layer 0 issue, but perhaps consider a set-up video for complete idiots...

**Comment by adamfk** [comment]
Can you join the discord group so we can troubleshoot?

**Comment by adamfk** [comment]
or can you add some detail of what you tried and what didn't work? I'm not really sure where you got stuck.

Have you tried following the install instructions at https://github.com/StateSmith/tutorial-2/tree/main/lesson-0 ?

If you type in `dotnet --version` on the command line, what do you get?

If you type in `dotnet script --version` on the command line, what do you get?

**Comment by adamfk** [comment]
Let me know if you still need help.

**Comment by lewsut** [comment]
Thanks buddy, I was away for a while I shall re try it and report back.
