### ISSUE TITLE
documentation - use `dotnet script` for mac osx

### ISSUE THREAD

**Issue by adamfk** [StateSmith/StateSmith#232]
![image](https://github.com/StateSmith/StateSmith/assets/274012/76afbe3b-5c1c-4cca-90f4-333be7062eb8)

**Comment by emmby** [comment]
For OSX I'm using `dotnet-script code_gen.csx` as documented without issue.

**Comment by adamfk** [comment]
Closing. We haven't had any other reports of `dotnet-script` not working on mac and it is working for others. Maybe an isolated issue.
