### ISSUE TITLE
add codeql workflow for static analysis

### ISSUE THREAD

**Issue by totocaca123** [StateSmith/StateSmith#251]

**Comment by adamfk** [comment]
Thanks for the suggestion. Hadn't heard of codeql before, but it looks pretty cool!

I'm pretty focused on improving user experience right now. Any chance you'd like to help set this up?

**Comment by adamfk** [comment]
Thanks for the PR 😃   
https://github.com/StateSmith/StateSmith/pull/259#pullrequestreview-2040684295
