### ISSUE TITLE
diagram only (no csx required)

### ISSUE THREAD

**Issue by adamfk** [StateSmith/StateSmith#285]
add support to `ss.cli` to compile diagrams to code without needing a csx file.

# Initial Work
- [x] add `--lang` and `--no-sim-gen` arg support to `ss.cli run`. Sim gen is on by default.
    - [x] ignore both for .csx files as they already control those options
- [x] scan for all recognized diagram types (drawio, plantuml)
- [x] ignore any files with this text: `statesmith.cli-ignore-this-file`
- [x] inspect diagram files for signs that they are meant for StateSmith
    - [x] drawio.svg should have `$STATEMACHINE`
    - [x] plantuml must have diagram name `@startuml MySmName` and also `-->`
- [x] filter out any of those diagrams already used by a csx file
- [x] filter out non StateSmith diagrams
- [x] emit messages for files ignored when run with verbose mode (stretch goal)

# Related Work
We need to lower reliance on expansions and or allow expansions inside diagram files #118

**Comment by adamfk** [comment]
@emmby you can try this out by installing a test release of the cli.

```
dotnet tool install --global StateSmith.Cli --version 0.8.2-diag-only-1
```

Then you can use the cli as normal, but it has another few options: (at bottom)
```
ss.cli run --help
Using settings directory: C:\Users\akruck\AppData\Roaming\StateSmith.Cli
StateSmith.Cli 0.8.2-diag-only-1+5fd14eca8da3bc97f3463498ccc03d61571f3b2b

  -h, --here         Runs code generation in this directory.

  -b, --rebuild      Ensures code generation is run. Ignores change detection.

  -u, --up           Searches upwards for manifest file.

  -r, --recursive    Recursive. Can't use with -i.

  -x, --exclude      Glob patterns to exclude

  -i, --include      Glob patterns to include. ex: `**/src/*.csx`. Can't use
                     with -r.

  --menu             Shows a terminal GUI with a choice menu. Don't use with
                     other options.

  --lang             Specifies programming language for transpiler. Ignored for
                     csx files.

  --no-sim-gen       Disables simulation .html file generation. Ignored for csx
                     files.
```

Use like `ss.cli run -hr --lang C99`. You should see something like this:

```
<snip>
── Checking diagram: `DiagOnlySm.plantuml` ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Diagram settings: Lang: C99, NoSimGen: False
Change detection not implemented yet. Rebuild for diagram. Issue #328.
Running diagram: `DiagOnlySm.plantuml`

StateSmith Runner - Compiling file: `../../StateSmith.CliTest/Run/examples/1/DiagOnlySm.plantuml` (no state machine name specified).
StateSmith Runner - State machine `DiagOnlySm` selected.
StateSmith Runner - Writing to file `../../StateSmith.CliTest/Run/examples/1/DiagOnlySm.h`
StateSmith Runner - Writing to file `../../StateSmith.CliTest/Run/examples/1/DiagOnlySm.c`
StateSmith Runner - Writing to file `../../StateSmith.CliTest/Run/examples/1/DiagOnlySm.sim.html`
StateSmith Runner - Finished normally.

...Skipping diagram `yes1.plantuml` already run by csx file `yes.csx`.
<snip>
Finished running diagrams.
```

**Comment by emmby** [comment]
Super cool! Seems to work well, it generated .c, .h, and .sim.html files for each of my diagrams
