### ISSUE TITLE
simulator - Better highlighting support for large diagrams in simulator

### ISSUE THREAD

**Issue by emmby** [StateSmith/StateSmith#308]
It's hard to see what's going on in large diagrams when states transition in the simulator.

Potential ideas:
- keep a zoomed out thumbnail when users zoom in: https://bumbu.me/svg-pan-zoom/demo/thumbnailViewer.html
- auto animate to the right state on transition if you're zoomed in. Would probably want to be able to turn this off.

**Comment by adamfk** [comment]
Some svg animation libs that look promising:

Good for animating edge path:
- https://github.com/merri-ment/lazy-line-painter
    - good demo https://codepen.io/camoconnell/pen/wRYELj
  
General purpose svg animation. 
- http://snapsvg.io/
    - I believe I used this for my [high tech mini golf course](https://www.youtube.com/watch?v=TLmVZwPT6XU) (the animated elves that jump) 
    - Could also be used to add a bit of animation to sm vertex size (grow when entered, shrink to normal when exited)

**Comment by emmby** [comment]
might be able to use `use`: https://stackoverflow.com/questions/25078634/can-i-re-use-the-same-svg-in-a-page-and-apply-different-css to include the svg twice (for thumbnail)

**Comment by emmby** [comment]
Filed #320 for better edge highlighting support
