### ISSUE TITLE
Replace simulator uses of sm.tracer. with sm.tracer?.

### ISSUE THREAD

**Issue by emmby** [StateSmith/StateSmith#310]
sm.tracer may not always be set

**Comment by adamfk** [comment]
when are you thinking that the tracer might not be set in the simulator? If we want to freeze history pane?

Might be nice to always call tracer in fsm, and then let higher js decide whether to show it or not?

**Comment by emmby** [comment]
See my explanation here: https://github.com/StateSmith/StateSmith/pull/311#discussion_r1625219086
