### ISSUE TITLE
improve exception printing & wording around `propagate exceptions`

### ISSUE THREAD

**Issue by adamfk** [StateSmith/StateSmith#375]
Before propagate exceptions enabled:
![image](https://github.com/user-attachments/assets/72d41451-5805-459a-bf2e-013628a05c62)

This looks weird like part of the Vertex info was cut off. I might have a flushing/buffer issue.

Running again:
![image](https://github.com/user-attachments/assets/1235ce16-b939-42f6-974e-485f7d940323)

I should also recommend users not use 'propagate exceptions' unless they want a detailed stack trace, but no context.

When propagate exceptions are enabled it is worse for user:
![image](https://github.com/user-attachments/assets/6b3dba71-bfc9-4904-a6ed-23e1a897e12b)

With dumping to file:
![image](https://github.com/user-attachments/assets/048d3045-7ebf-4825-9eac-c09ba6d188f6)

![image](https://github.com/user-attachments/assets/2e472db0-3dba-497a-bb59-68816cf4eaa2)

**Comment by adamfk** [comment]
Related areas of code:

https://github.com/StateSmith/StateSmith/blob/556c4612fddd1fab378ce7287623f260ad6813b7/src/StateSmith/Runner/SmRunnerInternal.cs#L79-L103

We throw an exception always because some `dotnet-script` versions fail to set exit code properly without an exception: https://github.com/StateSmith/StateSmith/blob/556c4612fddd1fab378ce7287623f260ad6813b7/src/StateSmith/Runner/SmRunner.cs#L117-L118

**Comment by Joebeazelman** [comment]
Instead of rethrowing using 'throw', try throw new Exception(e).
