### ISSUE TITLE
simulator - improve guard evaluation dialog

### ISSUE THREAD

**Issue by adamfk** [StateSmith/StateSmith#381]
Two main problems.

# No context about guards
There's no context about what state behavior is being evaluated. You just get prompted to evaluate some code.

![image](https://github.com/user-attachments/assets/3c3616aa-cf0d-4a9b-b0c6-cb723feef537)

We should include state name and state behavior as UML.

# Dialog is a bit confusing
OK for true and CANCEL for false isn't as intuitive

**Comment by adamfk** [comment]
I tried using https://sweetalert.js.org/guides/#advanced-examples, but it returns a promise. Will need to invest in async features for simulator first I believe.

**Comment by adamfk** [comment]
After change 
![image](https://github.com/user-attachments/assets/6b4eacf9-31e7-4b62-a172-f68486b6b146)

**Comment by krzysztofkuczek** [comment]
Hi,
I can see, that the problem is fixed, but today using ss.cli 0.19 got same behavior.
What should i do.
Thank you in advance.

<img width="1334" height="1364" alt="Image" src="https://github.com/user-attachments/assets/101b7ab5-2903-4a3d-8f9d-7f8d981d16a2" />

**Comment by adamfk** [comment]
Hi @krzysztofkuczek,

This dialog box is normal for evaluating guard expressions. It will be improved further in the future, but is better than it was.

Does pressing "OK" allow the transition to be taken?

**Comment by krzysztofkuczek** [comment]
Hi,
Yes it works, but in fact, the real expression is not taken under consideration....

**Comment by adamfk** [comment]
> Hi, Yes it works, but in fact, the real expression is not taken under consideration....

That is true. Because StateSmith lets user code contain anything, the simulator doesn't try to evaluate expressions. That's why it has to ask the user with the dialog box.

One day, StateSmith simulator will be smart enough to understand common expressions, but probably not for a few years.

Can you please open a new issue to improve simulator documentation to make this more clear? I'm currently traveling.
