### ISSUE TITLE
add `switch/case` based algorithm `Balanced2`

### ISSUE THREAD

**Issue by adamfk** [StateSmith/StateSmith#384]
See https://github.com/StateSmith/StateSmith/wiki/Algorithms

**Comment by adamfk** [comment]
Available for early testing in these releases:
* cli - `0.12.0-TEST-1`
* lib - `0.13.0-TEST-1`

**Comment by ptensschi** [comment]
Just a feedback on this: balanced2 helps saving precious ram/rom/runtime on very low-end uCs.
Great job improving an already great project.
