### ISSUE TITLE
how to add history feature(shallow-history/deep-history) in StateSmith

### ISSUE THREAD

**Issue by amigomcu** [StateSmith/StateSmith#56]
how to add history feature(shallow-history/deep-history) in StateMith

When need to transition out of a composite state, but later you wish to come back to the most-recent active substate of this composite state.

IBM Rational Rhapsody
![image](https://user-images.githubusercontent.com/23089799/195737491-dc01a1fb-772c-4969-9086-efd2f6a06ae8.png)
![image](https://user-images.githubusercontent.com/23089799/195737514-a8948024-658b-4825-88e8-93aeea8e2966.png)

https://www.ibm.com/support/pages/general-information-deep-and-shallow-history-connector-rhapsody

**Comment by adamfk** [comment]
Hi @amigomcu! StateSmith currently doesn't have deep/shallow history functionality built-in.

StateSmith will support it in the future, but for now, you can use a variable and additional state as shown below:
![image](https://user-images.githubusercontent.com/274012/195749097-d16b9a79-23c9-4c31-ba8d-6b20e54fd109.png)
[HistorySm.zip](https://github.com/StateSmith/StateSmith/files/9782009/HistorySm.zip)

I realize the work around above doesn't scale very well (especially for deep history).

When #40 is implemented, the `user_implemented_history_state` state above can be replaced with a choice pseudo state (a bit more efficient).

Let's keep this issue open to track progress of implementing history functionality.

**Comment by adamfk** [comment]
@amigomcu shallow and deep history functionality has been implemented in release 0.7.0. Documented here: https://github.com/StateSmith/StateSmith/blob/main/docs/history-vertex.md

Deep history is implemented a bit differently than how UML specifies it. Feedback and suggestions welcome.
