### ISSUE TITLE
Support hierarchical state machines

### ISSUE THREAD

**Issue by fredo514** [StateSmith/StateSmith#58]

**Comment by adamfk** [comment]
Hi @fredo514. The current version of StateSmith does support hierarchical state machines. We don't have all the features in UML yet, but was there something you were specifically looking for?

**Comment by fredo514** [comment]
Yeah, I created the issue before realizing it did. I closed it, sorry about that.

**Comment by adamfk** [comment]
No worries! Let me know if there are missing features that you need. It will help me prioritize future issues.
