### ISSUE TITLE
Python real time GUI front end

### ISSUE THREAD

**Issue by wmxsteel** [StateSmith/StateSmith#69]
You can use something like Dearpygui. It’s a intermediate gui and it already has a drag and drop diagramming feature

https://github.com/hoffstadt/DearPyGui

![2129F3F0-DE87-4CDF-A5CA-A3FA82E99F19](https://user-images.githubusercontent.com/112781450/209453944-fac79a84-5454-408a-b0b8-3f70a0049721.png)

https://preview.redd.it/g28jo9extpj91.gif?format=mp4&s=68db3547445c8ac072bd58b7a190de45d48bfcc0

Great work on state smith, I definately want to help out. I am a battery management systems controls engineer and I write embedded code on firmware for a living. 

https://www.reddit.com/r/DearPyGui/comments/wwsvv9/showcase_app_wedx_made_with_dear_pygui/

_edit by @adamfk to fix links._

**Comment by adamfk** [comment]
The imnodes editor looks really nice
https://github.com/Nelarius/imnodes

I'm not sure it would be good for nesting states, but it looks really helpful for data flow or filtering.

This demo screen looks like it has a kind of nesting though:
https://github.com/hoffstadt/DearPyGui/blob/assets/readme/nodes1.png

I'll document some of the features I'm looking for in a GUI soon. The main one is wanting to be able to collapse states/groups.

**Comment by adamfk** [comment]
@wmxsteel are you interested in pursuing Dearpygui now that we have draw.io integration working?

**Comment by adamfk** [comment]
I'm going to close this for now, but we can reopen if there is interest in this again.
